export const PRIMARY = '#071E22'
export const PRIMARY_DARK = '#1D7874'
export const PRIMARY_LIGTH = '#679289'
export const SECONDARY = '#F4C095'
export const SECONDARY_DARK = '#EE2E31'
export const PRIMARY_BUTTOM = '#messenger'
export const SECONDARY_BUTTOM = 'gray'
